### ISSUE TITLE
tcp: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1209]
Tracking misc smaller improvements to `tokio-tcp`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Features

- [ ] Expose `HUP` and `RDHUP` (#1182).
- [ ] Rethink std to/from conversions.

### Polish

- [x] `split` (#1217) bikeshed name & mod layout.
- [x] `split_mut` (#1289) bikeshed name & mod layout.
- [x] consider renaming `split_mut` -> `split (and current `split` -> `into_split`?).
- [x] combine into tokio-net crate (#1264).

### Testing

- [ ] Test notifications received by the net driver (i.e. waking tasks blocked on net resources).
- [ ] Split & concurrency
