### ISSUE TITLE
signal: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1243]
Tracking misc smaller improvements to `tokio-signal`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Update to `std::future`

- [x] follow the future / stream helper strategy from #1225.

### Polish
- [x] replace `crate::ctrl_c{,_with_handle}` with a `CtrlC` struct with `CtrlC::{new, with_handle}` methods (#1273)
- [x] replace `crate::windows::Event` with `crate::CtrlC` and `crate::windows::CtrlBreak` (#1331)
- [x] change `crate::unix::Signal::new` to accept a new `SignalType` enum (#1430)
  - this enum should represent all the common signal types (minus the obviously forbidden ones from `signal_hook`)
  - this enum should support a `Raw(c_int)` variant to allow specifying a signal using the libc definition (this unblocks anyone who wants to work with an OS specific signal which isn't defined in the `SignalType` enum)
   - this enum should be marked as nonexhaustive to avoid needing a breaking change to add new signal definitions (`tokio_signal` should be the only crate that ever needs to match on the types)
- [x] remove `libc` re-exports in favor of `SignalType` (#1430)
- [x] consider changing `crate::unix::Signal` to return `()` instead of the signum (#1330)
  - It *may* be useful to instead return the `SignalType` used during registration in case the caller wishes to listen to multiple signal streams and join them via `futures::select`
  - However, it is also entirely possible that the caller can simply do `Signal::new(sig_type).map(|()| sig_type)` if they wish to get this functionality, which keeps our API surface smaller
- [x] Make all `CtrlC`/`CtrlBreak`/`Signal` regular streams (*not* `IoStream`) since once they're up and registered there are not errors that are raised
- [x] Try to make the stream constructors return an `io::Result<Self>` instead of needing an intermediate init future (#1340)
    * this may be contingent on successfully registering all signal handlers and intermediate types without needing reactor/executor resources
- [x] Remove `IoFuture` / `IoStream` definitions
- [x] Bikeshed naming of `SignalKind` and its associated methods (#1457)

### Re-export

- [x] consider re-exporting `tokio_signal::CtrlC` as `tokio::signal::CtrlC` (#1491)

**Comment by ipetkov** [comment]
Hey @carllerche thanks for opening this, you've pretty much hit on the major API changes I was intending we update as part of the next breaking milestone (the lack of polish is largely leftover remains from older APIs which couldn't get fixed without breaking changes).

> Don't use i32 constants to represent signals (enum, structs, ...)
I was considering changing the futures to return `()` rather than `i32` (and let the caller track what event stream represents what if they need multiple signals). Signals are tightly coupled to the OS/libc, if we expose our own enum for signal types we might need to deal with OS specifics which I'm not sure is going to be worth the effort.

I'd also like to unify the Windows/Unix implementation differences (currently tracked in #1000).

One other idea I wanted to explore is improving the wake performance of signals. Right now all signals get woken each time due to past limitations where dropping the runtime would leak futures. Given this has been fixed I think it's worth revisiting as well.

**Comment by ipetkov** [comment]
Assigning this to myself, but for anyone interested in tackling any of this, feel free to ping me for questions/help or cc me on any opened PRs!

**Comment by carllerche** [comment]
@ipetkov cool! Also, just to be explicit. All the points in this issue are up for discussion. I just opened the issue with anything I thought of skimming the code. If you think they are all good ideas, then great :+1:

**Comment by marmistrz** [comment]
As of tokio-signal 0.2.8 ctrl-c handling under Windows doesn't work in MSYS2 bash, or in cmd if MSYS2 bash is its parent shell. Is this a known limitation or a bug?

To reproduce, use https://github.com/marmistrz/tokio-ctrlc-error, run the example and press ctrl+c before it times out.

**Comment by carllerche** [comment]
@marmistrz Could you open a dedicated issue for that?

**Comment by ipetkov** [comment]
Thanks for the feedback on #1430 @carllerche, moving the conversation here.

> At a bikeshed level, `SignalKind` isn't my favorite name... but it does work. It has precedence w/ `io::ErrorKind` and I can't think of anything better :).

I started out with `SignalType` but settled on `SignalKind` (which isn't really that much better either...). Happy to change to another name if anyone else has suggestions (maybe `SigNum`? `tokio_signal::Kind`?)

> I would probably avoid prefacing these fns w/ `signal`. Since the type is named `SignalKind`, using a signal prefix would be a stutter. Maybe use the full name, like `fn alarm`()`.

My initial thought was to keep things similar to the signal names themselves (where one would have used `libc::SIGFOO` before they can use `SignalKind::sigfoo` now), esp. since it could help with pasting a signal name in the docs and having the helper method come up. That said, I'm not terribly happy with the current naming either and I'd be fine with going with your suggestion if no other ideas are raised

**Comment by carllerche** [comment]
It looks like `std` avoids shortened names (for example, `io::ErrorKind` uses `InvalidInput` instead of `EINVAL`. I would follow that pattern.

`SignalKind` is the best option so far IMO. I would just stick w/ it.

**Comment by ipetkov** [comment]
I am proposing that we only export `CtrlC`/its equivalent via `tokio::signal` for now because it is the only API which is truly cross platform. The remainder of the APIs can be consumed directly through the new `tokio-net` crate via `tokio-net::signal`.

Thoughts from @carllerche or anyone else?

**Comment by naftulikay** [comment]
As a user I'd like to be able to catch and respond to a number of different signal types. I know that most of all of them are Unix specific, but I have an interest in being able to use this for general purpose signal catching.

**Comment by ipetkov** [comment]
@naftulikay signals are very much a Unix-specific concept. What do you mean by general purpose signal catching?

You can still register interest for any arbitrary Unix signal by using the platform specific APIs defined in the `tokio-net` crate. For now the consideration is to only reexport the truly cross platform APIs within the `tokio` crate for ease of use

**Comment by naftulikay** [comment]
I'm writing a process supervisor which needs to listen for term, quit, and chld signals. Being able to do that with Tokio is great for me as a user, as I get all the benefits of Tokio. 

Why are process signals in tokio::net?

**Comment by ipetkov** [comment]
> Why are process signals in tokio::net?

We decided to consolidate various crates together to make maintaining and releasing crates more streamlined (see #1264 for more info). `tokio-net` happens to include all the reactor and other internals needed for receiving and reacting to signals

**Comment by naftulikay** [comment]
My apologies: I'm looking through the 0.1 and 0.2 docs and not seeing anything in tokio::net. I'm mainly interested in understanding how the new API will work.

**Comment by ipetkov** [comment]
The internals will be the same, they're just migrating to where they're defined!
Unfortunately the alpha docs aren't being published on docs.rs, there's a tracking issue for fixing that in #1467

**Comment by carllerche** [comment]
@ipetkov  re: your proposal, that sounds good. My gut feeling is `tokio::signal::ctrl_c() -> CtrlC` feels more natural than `tokio::signal::CtrlC::new()`.

**Comment by ipetkov** [comment]
@carllerche yep that makes sense, I'll take a pass on updating the APIs to remove types where possible, and switch to using a dedicated constructor function rather than `::new()`

**Comment by ipetkov** [comment]
I believe all outstanding issues here have been resolved so I'm going to close this!
