### ISSUE TITLE
reactor: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1258]
Tracking misc smaller improvements to `tokio-reactor`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Polish

- [x] combine into tokio-net crate (#1264).

### Performance

- [ ] provide unsafe unsynchronized concurrent access to read / write notifications. The caller must ensure only one thread concurrently accesses read notifications and only one thread accesses write notifications.

### Testing

- [ ] concurrency when registering & cross thread notifications.

**Comment by carllerche** [comment]
Done mostly.
