### ISSUE TITLE
test: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1259]
Tracking misc smaller improvements to `tokio-test`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Features

- [ ] allow configuring the runtime from test macro.

### Polish

- [ ] focus on `task::spawn` instead of having two ways to do things.
- [ ] `waker_ref_count` should not count the task handle.

**Comment by carllerche** [comment]
Done I think.
