### ISSUE TITLE
timer: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1261]
Tracking misc smaller improvements to `tokio-timer`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### API

- [x] Consider switching `Delay::new(...)` -> `async fn delay(...)` (#1440).
- [ ] Consider renaming `Interval::next`, this would conflict w/ a `Stream` implementation.
- [ ] `Interval::new_interval` -> `new` and existing `new` -> `starting_at` (or something like that).
- [ ] Unify `fn sleep` with `fn delay`.

**Comment by sorz** [comment]
Should we impl `From<io::Error>` for `Elapsed` that converts it to `ErrorKind::TimedOut`?
It would enable chained expressions like `let len = stream.read(&mut buf).timeout(duration).await??;` in functions which return `io::Result`.

**Comment by carllerche** [comment]
@sorz that sounds good! I would take a PR for that 👍

**Comment by carllerche** [comment]
0.2 has shipped including most of this. Nothing further to do.
