### ISSUE TITLE
tokio: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1278]
Tracking misc smaller improvements to `tokio-sync`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Polish

- [x] audit re-exports
    - [x] how much should be re-exported in `tokio::executor`.
- [ ] switch I/O helpers to use `Buf` / `BufMut` / `Bytes`.
- [ ] improved way to block on a future (using enter is verbose / update tests).
- [x] switch examples back to return `Result<(), Box<Error>>`

### Examples

- [ ] don't use `Lock` in chat example.
