### ISSUE TITLE
meta: decide on a strategy regarding select! and fusing.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1895]
Currently, Tokio types do not implement `FusedFuture` and `FusedStream`. This makes it trickier to use those types with `futures::select!`.

## Questions

- [ ] Should Tokio types implement `FusedFuture` / `FusedStream`
    - [ ] If no, how (if at all) should we document this fact.
    - [ ] What about `tokio::stream::Fuse` (#2085)?
- [ ] Should we provide our own `select!`

**Comment by vorot93** [comment]
We have our own `select!` now.
