### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by taiki-e** [tokio-rs/tokio#2559]
This tracks the migration of CI to GitHub Actions from Azure Pipelines.

The following jobs need to be migrated.
Checked jobs have been migrated to GitHub Actions.

---

- [x] [test_tokio](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L9-L18); done in #2531
- [x] [test_sub_crates](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L20-L30); done in #2531
- [x] [test_integration](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L32-L37); done in #2531
- [ ] [test_build](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L39-L44)
- [ ] [miri](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L46-L49)
- [ ] [cross](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L51-L55)
- [ ] [check_features](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L57-L61)
- [ ] [minrust](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L63-L73)
- [ ] [rustfmt](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L75-L79)
- [ ] [clippy](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L81-L85)
- [ ] [docs](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L87-L91)
- [ ] [tsan](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L93_L96)
- [ ] [loom](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L98-L102)
- [ ] [deploy-docs](https://github.com/tokio-rs/tokio/blob/9f63911adc5b809fd3df7cfbb736897a86895e0c/azure-pipelines.yml#L104-L120)

Also, we need to look out what `ci/azure-is-release.yml` is actually doing and decide whether to add to GitHub Actions. https://github.com/tokio-rs/tokio/pull/2531#issuecomment-627726205

> I also haven't yet included the functionality from `azure-is-release.yml` because I haven't looked into how it interacts with the rest of the pipeline and I don't think it affects anything in what I've implemented so far.

**Comment by taiki-e** [comment]
I'm not sure if I have the bandwidth to do this now, but assign to self as a reviewer.

**Comment by taiki-e** [comment]
done in https://github.com/tokio-rs/tokio/pull/2680
