### ISSUE TITLE
meta: scheduled breaking API changes

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2879]
Placeholder issue tracking APIs that should change as they are discovered.

## I/O

* [x] remove `iovec` dependency. (#2882)
* [x] remove public `bytes` dependency (#2908)
  * [x] `impl FromStream for Bytes`

**Comment by taiki-e** [comment]
Closing -- done in #2882 and #2908.
