### ISSUE TITLE
meta: breaking API changes

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2928]
Tracks smaller breaking API changes that are left to make

## `io`

* [x] `Copy` should be private. (#2935)
* [x] `Seek` should be private. (#2935)
* [x] `ReadBuf` changes #2769.

## `net`

* [x] `TcpStream::poll_peek(&mut self, ...)` -> `&self`. (#2934)
* [x] `TcpStream::peek(&self)` -> `&self`. (#2934)
* [x] `UnixDatagram::try_send(&mut self, ...)` -> `&self`. (#2934)
* [x] `UnixDatagram::try_send_to(&mut self, ...)` -> `&self`. (#2934)
* [x] `UnixDatagram::try_recv(&mut self)` -> `&self`. (#2934)
* [x] `UnixDatagram::try_recv_from(&mut self)` -> `&self`. (#2934)
* [x] `UnixListener::accept(&mut self, ...)` -> `&self`. (#2934)
* [x] `UnixListener::poll_accept(&mut self, ...)` -> `&self`. (#2934)
* [x] `UnixListener::incoming(...)` -> remove for now (track `TcpListener::incoming()`)`. (#2934)
* [ ] Consider moving `split` fns off of `net` types into `-util`.
* [x] Revisit `UCred`, at the very least make struct fields private. (#2936)

## `sync`

* [ ] `Mutex::const_new()` -> `new()`. This may have to be conditionally `const` w/ `parking_lot` feature.
* [ ] Consider moving `Mutex::lock_owned()` -> `tokio-util`.
* [x] `mpsc::Sender::closed(&mut self)` -> `&self`. (#2939)
* [x] `mpsc::UnboundedSender::closed(&mut self)` -> `&self`. (#2939)
* [x] `broadcast` move error types into `broadcast::error` module. (#2937)

## `time`

* [x] `time::Delay` -> `time::Sleep`. (#2932)
* [x] Move error types into `time::error`. (#2938)

**Comment by akhilles** [comment]
Can https://github.com/tokio-rs/tokio/issues/2928 be added to the list?

**Comment by carllerche** [comment]
@akhilles I think you made a typo w/ your issue ref (you refed the current issue). If you have a proposal for an API change for 1.0, create a new issue for it :+1:

I don't think we are going to change any of the remaining APIs, so I will close this.
