### ISSUE TITLE
Potential performance improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#392]
This meta issue tracks all known performance issues.

* [ ] Improve scheduler heuristics (#145).
* [ ] Fix false sharing issues in thread pool (#422).
* [ ] Reduce contention in reactor (#426).
* [ ] Cache `clock::now` calls (https://github.com/tokio-rs/tokio/pull/381#issuecomment-393998588).

**Comment by seanmonstar** [comment]
Yes, there is, especially if you're deploying on AWS (or any other system that chooses to do the same): https://blog.packagecloud.io/eng/2017/03/08/system-calls-are-much-slower-on-ec2/

tl;dr - on AWS, it's a syscall to check the clock every single time.

**Comment by lnicola** [comment]
Related: https://stackoverflow.com/questions/42622427/gettimeofday-not-using-vdso

**Comment by carllerche** [comment]
Most of these are done. The clock one is tracked in #1181 now.
