### ISSUE TITLE
meta: Runtime metrics stabilization

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#4073]
Tracks the stabilization of runtime statistics.

RFC: #3845
PRs: #4043

## Roadmap

* [x] Release current implementation as unstable to crates.io (#4083)
* [x] Polish docs (remove TODO)
* [x] Add more counters
* [x] Write `tokio-metrics` providing a higher level api to be consumed that is easier to understand.
* [ ] Resolve open questions.
* [x] Validate design by evaluating users' experience reports.
    * [x] @Matthias247: [graph](https://media.discordapp.net/attachments/500336346770964480/893251797920129054/unknown.png?width=1272&height=866)

## Open questions

* Naming: Should the type be named `Metrics`, `Stats`, or `PerfCounters`.
* Should `RuntimeStats::workers()` return `&[WorkerStats]` or an iterator.
* Should there be a feature flag to enable stats explicitly?
  * Should there be a runtime Builder option to enable / disable stats.
* Builder API for more complex configurations, like histograms (#5685).
* `inc_budget_forced_yield_count` should become a per-worker metric.
* Should some current counters be lowered to internal counters?
  * steal_count
  * steal_operations
  * overflow_count

## Additional counters

* Duration between last two polls.
    *  There are open questions related to how this should be used.
* Worker queue depth
    * It is unclear how this should be tracked.

**Comment by carllerche** [comment]
@LucioFranco @Matthias247 any opportunities to try using the metrics?

**Comment by Matthias247** [comment]
I was on vacation and after that mostly block on other things. But I might be able to try this out this week.

I will however say upfront that I'll expect mostly to report back on the general accessor APIs and how integration into an application will look like. I think that putting `poll_count`/`steal_count`/etc on a dashboard will not be super useful for most people, because the numbers in itself have no significant meaning. They don't necessarily indicate that something is right or wrong. The not-yet-implemented timing metrics are more interesting, because they would indicate issues with code in tasks blocking too long. I will nevertheless check and see how the other metrics would look like.

**Comment by carllerche** [comment]
We should add a counter tracking the number of "false-positive" runtime wakeups. This would be incremented when a worker wakes up without having any work to do.

**Comment by eadventurous** [comment]
> The not-yet-implemented timing metrics are more interesting, because they would indicate issues with code in tasks blocking too long.

I second this. In our project built on tokio, we implemented a custom [macro](https://github.com/hyperledger/iroha/blob/d7c0b582920f036548768b501769e5785cf709db/futures/derive/src/lib.rs) to track poll times. It would be very useful to have it in tokio.

**Comment by zonyitoo** [comment]
It have been quite a long time, what's the status of this issue? @carllerche 

It is quite useful for library authors to know the number of workers in the current Runtime.

**Comment by LucioFranco** [comment]
Work has stalled a bit on this, but we would be happy to mentor people on this work.

**Comment by LucioFranco** [comment]
I don't believe this is ready for stabilization.

**Comment by Noah-Kennedy** [comment]
What's the status on this? It looks like nothing has happened for a while here.

@LucioFranco, I would be willing to pick up where you left off here, I just need to know what needs done.

**Comment by LucioFranco** [comment]
I believe we have a bunch of metrics in the runtime now and `tokio-metrics` has an initial version published. @carllerche would know the rest. Go ahead and pick it up, I won't have time for a bit. Happy to be tagged for reviews tho.

**Comment by carllerche** [comment]
I aim to stabilize this feature by EOY.

As I look at the current counters, I think some of the more "scheduler implementation detail" counters should be switched to be [internal counters](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/scheduler/multi_thread/counters.rs). For example, the following counters are more useful for debugging the scheduler than debugging application performance issues:

* steal_count
* steal_operations
* overflow_count

**Comment by carllerche** [comment]
At the risk of reopening bikeshedding, we must also decide on a name: metrics, stats, or counters.

Given that we have more than just counters, I guess that probably rules out counters as a name.

**Comment by Noah-Kennedy** [comment]
Artificial Indecisiveness
