### ISSUE TITLE
meta: task dump stabilization

### ISSUE THREAD

**Issue by jswrenn** [tokio-rs/tokio#5638]
**Feature Request:** #5457 

**PRs:**
- https://github.com/tokio-rs/tokio/pull/5608

**Roadmap:**
- Runtime Support
  - [x] Implement task dumps for multi-thread runtime. ([PR](https://github.com/tokio-rs/tokio/pull/5608))
    - [ ] Support capturing task dump of current-thread runtime from outside runtime context.
  - [ ] Implement task dumps for multi-thread runtime.
- Trace Quality Improvements
  - [ ] Instrument all tokio leaves.
  - [ ] Instrument frames with extra metadata (e.g., function arguments).
  - [ ] Provide a public API for instrumenting frames.
  - [ ] Increase platform support.
  - [ ] Maintain insertion order of frames in trace output.
- Task Dump Improvements
  - [ ] Include additional task metadata:
    - [ ] spawn location
    - [ ] name
    - [ ] ID 
  - [ ] Ensure that  `FuturesUnordered` and `LocalSet` futures are included in dumps.
  - [ ] Add functionality for dumping subset of tasks.
  - [ ] Include Very Stuck Tasks
- Remove External Dependencies
  - [ ] Remove `backtrace-rs` dependency.
- Misc
  - [ ] Clean up `#[cfg]`s.

**Comment by carllerche** [comment]
@jswrenn Something I noticed (and I updated the checklist).

The `trace::Context` field added to `runtime::Context` has a `Vec`, which has a drop implementation. We need to make sure that `runtime::Context` does not require a drop implementation to take advantage of const thread locals.

I know `scheduler::Handle` **currently** requires one, but I have a plan to remove that.

**Comment by jswrenn** [comment]
Thanks for reporting the panic issue — I had really hoped we fixed that, but I guess not. I'll look into that ASAP.

I *believe* the behavior of taskdumps in the presence of very-stuck-tasks _should_ be to hang. Tasks dumps work by waiting for all polls to complete, then re-polling all tasks in a special tracing mode. If a poll never completes, this synchronization point cannot be reached and a taskdump cannot be produced. (That's not ideal, but an infinite-looping `poll` is where a traditional debugger becomes the better tool of choice, anyways.)

I would only expect task dumping to produce an empty string in cases when the dumped runtime has no work to do. This might happen if you have multiple runtimes and are polling one that happens to have no work to do. 

That said, the fact that you're running into #6185 means that some of my assumptions are wrong.

**Comment by scottlamb** [comment]
> I would only expect task dumping to produce an empty string in cases when the dumped runtime has no work to do. This might happen if you have multiple runtimes and are polling one that happens to have no work to do.

Hmm. I do have multiple runtimes (I give `quinn` connections their own single-threaded runtime due to not-yet-understood quinn-rs/quinn#1433), but I'm only dumping the main multi-threaded runtime, and it's returning a bunch of tasks, some with meaningful traces and some with empty strings. I'm assuming the other runtimes' tasks wouldn't show up in this runtime's dump at all?

**Comment by jswrenn** [comment]
I *think* empty strings could also arise if the tasks are simple and aggressively inlined. Are you experiencing this in debug builds? 

> I'm assuming the other runtimes' tasks wouldn't show up in this runtime's dump at all?

Correct.

**Comment by sukhmel** [comment]
I came here searching for what could lead to empty traces, too. I do have librdkafka that polls itself, I think, but everything is being run only with `tokio` and there are sometimes quite a few tasks with empty `task.trace()`
