### ISSUE TITLE
Improve Tokio's blocking capabilities

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#629]
## Motivation

Tokio uses cooperative scheduling, requiring tasks to execute for short periods of time before yielding back to the executor. There are cases that require a task to execute for longer periods of time. For example, reading and writing to files or performing long running CPU computations.

To handle this, Tokio should provide an API to allow performing work that would otherwise block the executor.

Currently, Tokio provides a `blocking` function, but this function only works with the concurrent runtime. It also has limitations (#589) which prevents it from being general purpose.

## Proposal

Tokio should provide a general purpose blocking pool (#588). While this pool will not be as efficient as the `blocking` function, it will not suffer from the limitations of #589.

Then, Tokio APIs that require blocking will be able to pick the strategy that best fits.

For example, `tokio_fs::File` could use `blocking` if it is available and fallback to the general purpose pool if it is not available. Reading from `stdin` would always use the blocking pool.

## TODO

* [ ] #588 - Implement the blocking pool.
* [ ] - Update `tokio-fs` to use the various pools appropriately.
* [ ] #618 - Improve `blocking` documentation.

**Comment by tobz** [comment]
For the sake of surfacing concerns: is there any reason we wouldn't want to move all blocking to this general approach i.e. filesystems operations?

That's the Erlang (and others, I'm sure) approach of moving all I/O to a separate pool.  Is there much of a benefit to the current `blocking` trick beyond not having an idle thread pool sitting around that may never be used?

**Comment by carllerche** [comment]
The `blocking` trick is significantly faster, which only matters if the actual "blocking" operation is short or might not really be blocking.

For example, when reading from a file, the next chunk of data might be in the cache, in which case a call to `File::read` doesn't actually block.

**Comment by stjepang** [comment]
Is `blocking()` a good solution for CPU bound tasks at all? If we use `blocking()` to spawn thousands of CPU bound tasks at a time, that means we end up with thousands of threads.

My opinion is that `blocking()` should be used for blocking IO calls only, while for CPU bound tasks we should have better integration with Rayon. For example, I wish the following was possible:

```rust
let total_sum = await!(rayon::future(|| v.par_iter().sum()));
```

Rayon has already become *the* threadpool for computation (and it's very good at it!) so perhaps we should defer such tasks to it?

**Comment by carllerche** [comment]
@stjepang Sorry, for "long running" I mean too long for a non-blocking event loop. For example, TLS decoding. I don't think TLS decoding makes sense to defer to rayon for.

I don't intend to try to reach for any cases that rayon is good for, any sort of computation that can be parallelized should be run with rayon.

**Comment by carllerche** [comment]
#588 and #1178 track enough. This issue is not necessary.
