### ISSUE TITLE
Automate releasing crates

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#801]
Releasing Tokio crates is tedious and error prone. This makes it a good candidate for automation via a GitHub bot.

## Overview

* [ ] Define release process #800.
* [ ] Automate CHANGELOG generation.
* [ ] Create tool that generates release patch, including changelog entries (refs: #765).
* [ ] Add GitHub check ensuring bot can generate changelog for PR.
* [ ] Bot automatically pushes crates once release PR is merged.
* [ ] Bot generates release PRs on a weekly basis.

Each of these steps are useful standalone.

## Misc thoughts

* The bot should not automatically deploy breaking change releases. As such, breaking changes need to be tracked somehow. There should probably be a `breaking change` GitHub label as well as breaking change commits should be annotated somehow in the git history?

Refs: #765

**Comment by LucioFranco** [comment]
Probably the best changelog generator I have found so far is [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator). It uses PRs to generate a changelog, the PRs can then be labeled to indicate if its a bug, enhancement, or maintenance. I think if the process for creating and labeling PRs was standardized then this could work quite well. Though, it does not generate a changelog per crate.

**Comment by davidbarsky** [comment]
Quick clarifying question—why a CHANGELOG over a GitHub release? GitHub releases might be less tricky to work with than a CHANGELOG due to the programatic interface, but it's possible the tricky bits of this process _aren't_ interacting with GitHub.

**Comment by carllerche** [comment]
@davidbarsky how would things work w/ github releases?

**Comment by LucioFranco** [comment]
@davidbarsky I would imagine the changelog is there to capture the entire history and once a crate is ready for release its changelog portion that was unreleased now just gets copied into a github release. I think using both options is not mutually exclusive.

**Comment by aug2uag** [comment]
I'd love to do this for you.

**Comment by carllerche** [comment]
@aug2uag great! I started hacking on some stuff. Ping me in https://gitter.im/tokio-rs/dev. I'll also work on making my progress open and we can collaborate in that project. I'll update this issue next week.

**Comment by carllerche** [comment]
Collapsing crates has reduced the importance of this. Closing due to inactivity.
